### ISSUE TITLE
Adicionar enunciados

### ISSUE THREAD

**Issue by Uefa41** [DanielDPereira/OBI#2]
Eu diria que seria interessante ter uma cópia dos enunciados diretamente na pasta do exercício

**Comment by DanielDPereira** [comment]
Concordo Raad, seria bom colocarmos um README com o exercício

**Comment by DanielDPereira** [comment]
Vou me encarregar de fazer isso durante essa semana

**Comment by DanielDPereira** [comment]
Eu quero reorganizar o repositório, colocando primeiro o ano e depois os níveis, como acha melhor?

**Comment by Uefa41** [comment]
Desculpa, só vi agora. Acho melhor mesmo por os anos e depois os níveis
